[package]
name = "rawrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
jargon-args = "0.2.5"
async-std = "1.12.0"
serde = { version = "*", features = ["derive"] }
toml = "*"