syllable_order = "cv(c)"

forbid_str = [
    "uù",
    "iì",
]

forbid_const_cluster = true
forbid_vowel_cluster = true

consonants = [
    'c',
    'l',
    'n',
    'p',
    's',
    't',
    'ù',
    'ì',
]

vowels = [
    'a',
    'e',
    'i',
    'o',
    'u',
]
